

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app_network
    expose:
      - "9000" # Expõe a porta do PHP-FPM para o Nginx

  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www
    ports:
      - "8087:87"
    networks:
      - app_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2603
      MYSQL_DATABASE: sl
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
